"""
Django settings for deIdentification project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from jupyter_server.auth import passwd

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def is_true(value):
    if str(value).lower() in ["true", "1", "yes", "y"]:
        return True
    return False


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-81e&%b$hwo15=#dwuv8pr(tz+8$eit5jr&_(ey=v@e3=&8u(b-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = is_true(os.environ.get("DEBUG", "true"))
DISABLE_AUTHENTICATION = is_true(os.environ.get("DISABLE_AUTHENTICATION", "true"))


ALLOWED_HOSTS = ["*"]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000","http://localhost:3000","http://127.0.0.1:3000"]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000","http://127.0.0.1:3000"
]
CORS_ALLOW_HEADERS = ['*']
# CORS_ALLOW_HEADERS = [
#     "accept",
#     "accept-encoding",
#     "authorization",
#     "content-type",
#     "dnt",
#     "origin",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
# ]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "deIdentification",
    "nd_api",
    "rest_framework",
    "worker",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "deIdentification.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "deIdentification.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


BATCH_SIZE_DURING_DE_IDENTIFICATION = int(os.environ.get("BATCH_SIZE_DURING_DE_IDENTIFICATION", 100000))
PATIENT_ID_PREFIX = 10000000

# Jupyter Lab settings
NOTEBOOK_ARGUMENTS = [
    "--ip",
    "0.0.0.0",
    "--port",
    "8888",
    "--NotebookApp.password",
    passwd("ND@123"),
]

CREATE_SAVEPOINT_IN_TRANSACTION = is_true(
    os.getenv("CREATE_SAVEPOINT_IN_TRANSACTION", True)
)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DE_IDENTIFICATION_DB_NAME", "deid_prod_v2"),
        "USER": os.getenv("DE_IDENTIFICATION_DB_USER", "postgres"),
        "PASSWORD": os.getenv("DE_IDENTIFICATION_DB_PASSWORD", "postgres"),
        "HOST": os.getenv("DE_IDENTIFICATION_DB_HOST", "localhost"),
        "PORT": os.getenv("DE_IDENTIFICATION_DB_PORT", 5432),
    }
}
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Add a global templates directory if needed
        "APP_DIRS": True,  # Ensure this is True to enable app-specific templates
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

KEYCLOAK_CLIENT_ID = os.environ.get("KEYCLOAK_CLIENT_ID", "localhost-dev-client")
KEYCLOAK_REALM_NAME = os.environ.get("KEYCLOAK_REALM_NAME", "localhost-dev")
KEYCLOAK_CLIENT_SECRET = os.environ.get("KEYCLOAK_CLIENT_SECRET", "p4BoX25BUe37K9b7gCuo4pL8vwdnUPf8")
KEYCLOAK_URI = os.environ.get("KEYCLOAK_URI", "http://localhost:9090/")
KEYCLOAK_ADMIN_USERNAME = os.environ.get("KEYCLOAK_ADMIN_USERNAME", "rohit")
KEYCLOAK_ADMIN_PASSWORD = os.environ.get("KEYCLOAK_ADMIN_PASSWORD", "rohit")


DATA_DUMP_DESTINATION_PATH = os.environ.get("DATA_DUMP_DESTINATION_PATH", "/srv/data/dump_data")

CLOUD_BUCKET_NAME = os.environ.get("CLOUD_BUCKET_NAME")
CLIENT_NAME = os.environ.get("CLIENT_NAME", "DEIDENTIFICATION_CLIENT")


DEFAULT_OFFSET_VALUE = int(os.environ.get("DEFAULT_OFFSET_VALUE", 34))
STATS_GENERATION_MAX_WORKER_COUNT = int(os.environ.get("STATS_GENERATION_MAX_WORKER_COUNT", 20))
MAX_FAILURE_COUNT=int(os.environ.get("MAX_FAILURE_COUNT", 1))
