# Generated by Django 4.2.17 on 2025-01-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DbDetailsModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_name", models.CharField(max_length=255, unique=True)),
                ("source_db_config", models.JSONField(default=dict)),
                ("destination_db_config", models.JSONField(default=dict)),
                ("run_config", models.JSONField(default=dict)),
                (
                    "stats_generated_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (3, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("db_stats", models.JSONField(default=dict)),
                ("is_phi_marking_locked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PatientMappingTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_id", models.BigIntegerField(db_index=True)),
                ("nd_patient_id", models.BigIntegerField()),
                ("date_offset", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhiTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_id", models.BigIntegerField(db_index=True)),
                ("phi_details", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EncounterMappingTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("encounter_id", models.BigIntegerField(db_index=True)),
                ("nd_encounter_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nd_api.patientmappingtable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TableDetailsModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(max_length=255)),
                ("size", models.CharField(max_length=100, null=True)),
                ("rows_count", models.IntegerField(null=True)),
                ("table_details_for_ui", models.JSONField(default=dict)),
                (
                    "table_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (3, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("failure_remarks", models.JSONField(default=dict, null=True)),
                ("is_phi_marking_done", models.BooleanField(default=False)),
                ("is_qc_failed", models.BooleanField(default=None, null=True)),
                ("is_qc_passed", models.BooleanField(default=None, null=True)),
                ("is_phi_marking_locked", models.BooleanField(default=None, null=True)),
                (
                    "db",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables_details",
                        to="nd_api.dbdetailsmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("table_name", "db")},
            },
        ),
    ]
