# Generated by Django 4.2.17 on 2025-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabledetailsmodel",
            name="run_config",
            field=models.JSONField(default=dict),
        ),
    ]
