# Generated by Django 4.2.17 on 2025-02-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0002_tabledetailsmodel_run_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDump",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dump_name", models.CharField(max_length=200, unique=True)),
                ("config", models.JSONField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (3, "Failed"),
                            (4, "Interrupted"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="tabledetailsmodel",
            name="cloud_uploaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tabledetailsmodel",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tabledetailsmodel",
            name="md5sum",
            field=models.CharField(default=None, null=True),
        ),
    ]
