# Generated by Django 4.2.17 on 2025-02-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0003_datadump_tabledetailsmodel_cloud_uploaded_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoreRowsDeIdentificaiton",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_name", models.CharField(max_length=200, unique=True)),
                ("table_name", models.CharField(max_length=200, unique=True)),
                ("row", models.JSONField(default={})),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
