# Generated by Django 4.2.17 on 2025-02-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0004_ignorerowsdeidentificaiton"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ignorerowsdeidentificaiton",
            name="db_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="ignorerowsdeidentificaiton",
            name="table_name",
            field=models.CharField(max_length=200),
        ),
    ]
