# Generated by Django 4.2.17 on 2025-02-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0005_alter_ignorerowsdeidentificaiton_db_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestoreDump",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("config", models.JSONField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (3, "Failed"),
                            (4, "Interrupted"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dump",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restore_details",
                        to="nd_api.datadump",
                    ),
                ),
            ],
        ),
    ]
