# Generated by Django 4.2.17 on 2025-03-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nd_api', '0006_restoredump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledetailsmodel',
            name='is_qc_failed',
        ),
        migrations.RemoveField(
            model_name='tabledetailsmodel',
            name='is_qc_passed',
        ),
        migrations.AddField(
            model_name='tabledetailsmodel',
            name='qc_result',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tabledetailsmodel',
            name='qc_status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed'), (3, 'Failed')], default=0),
        ),
    ]
